title: Mon Blog
description: "Ceci est un blog personnel où je partage mes pensées."
author: "Pascal Larouche"
logo: Images/Roman_baths_2014_70.jpg
baseurl: "" # Pour un usage avec un sous-domaine
url: "https://yourusername.github.io"

# Thème
theme: minima # Par exemple, vous pouvez utiliser 'minima', 'jekyll-theme-slate', etc.
